"""initial migration

Revision ID: ca1a10ca8a2d
Revises: 485ffc080bbd
Create Date: 2016-03-31 17:12:40.185214

"""

# revision identifiers, used by Alembic.
revision = 'ca1a10ca8a2d'
down_revision = '485ffc080bbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
