"""initial migration

Revision ID: dce079e8b25d
Revises: 177f21d45662
Create Date: 2016-04-01 14:50:21.953568

"""

# revision identifiers, used by Alembic.
revision = 'dce079e8b25d'
down_revision = '177f21d45662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
